title: Hartwell Baptist Church
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://camprhino.org/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
paginate: 5
paginate_path: "/updates/page:num/"


# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js
  - bower_components
keep_files:
  - css
  - assets/css
  - assets/js





author:
- Mark Coffey

