name: 'Thailight.org'
logo_image_path: 
logo2_image_path: 
main_image: 
phone: 
email: 
facebook: 
twitter:
youtube:
instagram:
address: 
address2:
City: 
State: 
Zip: 
mission_board_image: 
sending_church_image: 
main_blog_image: 
main_sermon_image: 
default_calendar_image: 
Google_calendar_id: 
tinyletter: https://tinyletter.com/pastorryanhayden